/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontSize: {
        xs:    ['0.75rem',  { lineHeight: '1.4',  letterSpacing: '0.01em' }],
        sm:    ['0.875rem', { lineHeight: '1.5',  letterSpacing: '0.01em' }],
        base:  ['1rem',     { lineHeight: '1.6',  letterSpacing: '0.01em' }],
        lg:    ['1.125rem', { lineHeight: '1.6',  letterSpacing: '0em' }],
        xl:    ['1.25rem',  { lineHeight: '1.5',  letterSpacing: '0em' }],
        '2xl': ['1.5rem',   { lineHeight: '1.4',  letterSpacing: '-0.01em' }],
        '3xl': ['1.875rem', { lineHeight: '1.3',  letterSpacing: '-0.02em' }],
        '4xl': ['2.25rem',  { lineHeight: '1.2',  letterSpacing: '-0.02em' }],
        '5xl': ['3rem',     { lineHeight: '1.1',  letterSpacing: '-0.03em' }],
        '6xl': ['3.75rem',  { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        '7xl': ['4.5rem',   { lineHeight: '1.0',  letterSpacing: '-0.04em' }],
        '8xl': ['6rem',     { lineHeight: '1.0',  letterSpacing: '-0.04em' }],
        '9xl': ['8rem',     { lineHeight: '0.95', letterSpacing: '-0.04em' }],
      },
      fontFamily: {
        heading:   ['"Be Vietnam Pro"', 'sans-serif'],
        paragraph: ['Nunito', 'sans-serif'],
      },
      colors: {
        destructive:             '#EF4444',
        'destructive-foreground':'#FFFFFF',
        muted:                   '#F0FAF9',
        'muted-foreground':      '#6B7280',
        background:              '#F8FFFE',
        secondary:               '#D1FAF5',
        foreground:              '#1A2E2B',
        'secondary-foreground':  '#1A2E2B',
        'primary-foreground':    '#FFFFFF',
        primary:                 '#0D9488',
        'primary-light':         '#14B8A6',
        'primary-dark':          '#0F766E',
        accent:                  '#F59E0B',
        'accent-foreground':     '#FFFFFF',
        card:                    '#FFFFFF',
        'card-foreground':       '#1A2E2B',
        border:                  '#CCFBF1',
        input:                   '#E5F7F5',
        ring:                    '#0D9488',
        surface:                 '#EBF8F6',
      },
      borderRadius: {
        'none': '0',
        'sm':   '6px',
        DEFAULT:'10px',
        'md':   '12px',
        'lg':   '16px',
        'xl':   '20px',
        '2xl':  '24px',
        '3xl':  '32px',
        'full': '9999px',
        'card': '16px',
        'btn':  '10px',
        'tag':  '8px',
      },
      boxShadow: {
        'soft':    '0 2px 12px 0 rgba(13,148,136,0.08)',
        'card':    '0 4px 24px 0 rgba(13,148,136,0.10)',
        'card-hover': '0 8px 40px 0 rgba(13,148,136,0.16)',
        'btn':     '0 2px 8px 0 rgba(13,148,136,0.20)',
        'inner':   'inset 0 2px 6px 0 rgba(13,148,136,0.08)',
      },
      backgroundImage: {
        'hero-gradient':   'linear-gradient(135deg, #F0FAF9 0%, #ECFDF5 50%, #F0F9FF 100%)',
        'card-gradient':   'linear-gradient(180deg, rgba(255,255,255,0) 60%, rgba(13,148,136,0.04) 100%)',
        'teal-gradient':   'linear-gradient(135deg, #0D9488 0%, #14B8A6 100%)',
        'accent-gradient': 'linear-gradient(135deg, #F59E0B 0%, #FCD34D 100%)',
        'blob-1':          'radial-gradient(ellipse at 20% 50%, rgba(20,184,166,0.15) 0%, transparent 60%)',
        'blob-2':          'radial-gradient(ellipse at 80% 20%, rgba(245,158,11,0.10) 0%, transparent 50%)',
        'blob-3':          'radial-gradient(ellipse at 60% 80%, rgba(13,148,136,0.12) 0%, transparent 55%)',
        'dots':            'radial-gradient(circle, rgba(13,148,136,0.15) 1.5px, transparent 1.5px)',
        'grid-soft':       'linear-gradient(rgba(13,148,136,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(13,148,136,0.06) 1px, transparent 1px)',
      },
      backgroundSize: {
        'dots-sm': '20px 20px',
        'dots-md': '32px 32px',
        'grid-md': '40px 40px',
      },
      animation: {
        'marquee':       'marquee 24s linear infinite',
        'float':         'float 6s ease-in-out infinite',
        'float-slow':    'float 9s ease-in-out infinite',
        'float-delayed': 'float 7s ease-in-out infinite 2s',
        'pulse-soft':    'pulse-soft 3s ease-in-out infinite',
        'spin-slow':     'spin 20s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-12px)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '0.6' },
          '50%':      { opacity: '1' },
        },
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [],
}